import React from 'react';

const About = () => (
	<div id="aboutwrap" className="container">
		<div  className="row centered mt mb">
			<div  className="col-lg-8 col-lg-offset-2">
				<h3 className="heading"><strong>About</strong></h3>
				<p className="text-justify">I've always been a technology geek, friends and family would come to me to solve their computer related problems, so one fine day I  realized that since I love doing it as a hobby why not do it professionally! I decided to drop out of college (I used to study history, I still love reading history books but I love tech even more) and I started fixing PC's on the side. After that, I took a few <a href="http://www.mycertprofile.com/Profile/1947938383" target="_blank" rel="noopener noreferrer">Microsoft Certificates</a> and those helped me land my first full time IT job - I got a remote position as a tech support specialist working for a 
				<a href="http://learninglibrary.com/education" target="_blank" rel="noopener noreferrer"> Canadian e-learning  company</a>. I worked in tech support for little over two and a half years, while I enjoyed the job,  it felt a little too easy and I needed new challenges. That is when I decided to start learing to code. In January 2017 I discovered <a href="https://www.freecodecamp.org/mickey0001" target="_blank" rel="noopener noreferrer"> Free Code Camp</a> and started working on their curriculum. I completed their <a href="https://www.freecodecamp.org/mickey0001/front-end-certification" target="_blank" rel="noopener noreferrer"> Front-End Development Certification</a> on February 2nd 2018. I'm currently focusing on getting better at React and working on FFC's Data Visualization Certification.</p>
				<p className="text-justify">Since I started learning web development I completed a lot of tutorials (over 200 hours in Udemy courses) but I realized that in order to retain what I've learned I needed to start making projects. I started small, making a few websites for friends and doing a bit of <a href="https://www.upwork.com/o/profiles/users/_~01a70d936afbbff30e" target="_blank" rel="noopener noreferrer"> freelancing</a> on the side. You can check out my <a href="https://github.com/Mickey0001" target="_blank" rel="noopener noreferrer"> GitHub profile</a>  to see the code for the projects I worked on. When I get stuck I resort to Google-fu and usually end up finding answers on sites like <a href="https://stackoverflow.com/users/7443287/mirza-sisic" target="_blank" rel="noopener noreferrer"> StackOverflow</a> and occassiinaly I'll even post a questions there, what can I say I like to live dangerously! Another helpful resource has been the <a href="https://gitter.im/realtoughcandy-community/Lobby" target="_blank" rel="noopener noreferrer"> RTC Gitter community</a>, a chat room full of friendly nerds willing to help each other out, also there is a thing called the Mentorship Mondays where we meet weekly via Google Hangouts to learn together! Check out my blog - <a href="https://juniorlearnstocode.blogspot.ba/" target="_blank" rel="noopener noreferrer"> Junior Learns To Code </a> where I share my thoughts and describe my coding journey. In the projects section you can see examples of my work and don't be shy to reach out, I'd love to help you to get your website up and running!</p>
 			</div>
 		</div>
 	</div>
);
export default About;